### ISSUE TITLE
As a user, I want to resize annotations so that I can add extra comments to my document

### ISSUE THREAD

**Issue by kuthatikk** [WSU-CEG-6110-4410/Agile-Tuskers#1]
## Todo

 - [ ] create a class that has annotation functionalities
 - [ ] test functions in annotation class
 - [ ] add a button to UI that allows a user to annotate a pdf

**Comment by mrudhul-eng** [comment]
user story completed
